#!/usr/bin/env bash

echo "==> running post-merge"

git rev-parse HEAD > commit.txt
composer update
cd ./web/app/themes/coop-tech-oowp-theme
composer install
npm install
gulp
./node_modules/gulp/bin/gulp.js  # in case gulp not in $PATH

git fetch && git log ORIG_HEAD..origin/master --pretty=format:"%s - %ar by %an (%h)"

echo "==> post-merge complete"
